analyzer:
  kafka:
    consumer:
      sensor_snapshot:
        bootstrap.servers: "localhost:9092"
        key.deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
        value.deserializer: "ru.yandex.practicum.SensorSnapshotDeserializer"
        group.id: "analyzer-consumer"
        enable.auto.commit: false
      hub_event:
        bootstrap.servers: "localhost:9092"
        key.deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
        value.deserializer: "ru.yandex.practicum.HubEventDeserializer"
        group.id: "analyzer-consumer"
        enable.auto.commit: false
      poll_duration_seconds:
        sensor_snapshot: 10
        hub_event: 10

grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

spring:
  jpa:
    hibernate.ddl-auto: none
    properties.hibernate.format_sql: true
  sql.init.mode: always
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/telemetry_analyzer"
    username: "postgres"
    password: "password"